version: "3.8"
services:

  nodered:
    image: nodered/node-red
    container_name: node-red
    environment:
    - SERVICE_NAME=node-red
    ports:
    - "1880:1880"
    volumes:
     - ./node-red/modules:/root/.node-red
